import { useContext } from "react";
import Head from "next/head";

// context
import _appContext from "../context/_appContext";

// components
import Card from "../components/Card";

// hooks
import useHotItems from "../hooks/useHotItems";

export default function Home() {
  const { isMobile } = useContext(_appContext);
  const { hotItems, loading } = useHotItems();

  return (
    <>
      <Head>
        <title>Pride Shop | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style jsx>{`
        div {
          font-family: "Julius Sans One", sans-serif;
        }
      `}</style>
      <div className="text-center text-xl mb-10">🔥 Hot Items! 🔥</div>
      <div className="mx-12 smaller:mx-16 sm:mx-24 md:mx-20 lg:mx-[10vw] grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-8">
        <Card />
        <Card />
        <Card />
        <Card />
        <Card />
        <Card />
        <Card />
      </div>
    </>
  );
}
